### ISSUE TITLE
TODO: Instructions to contributors for installing the development branch

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#199] opened 2012-08-14 06:39 UTC
Today makes the fourth time someone in irc has needed help with getting the development branch installed (counting myself). While it will (very very soon now ;P) be merged into master, I assume new development will continue on it, and though hopefully it will be merged on a regular basis, I assume it will always be the best place to start for those wanting to hack on tower itself. Thus the need for easy to follow instructions for cloning it from github and installing it , perhaps in the readme or wiki.

**Comment by avaranovich** [comment] 2012-08-14 07:49
Based on IRC discussion, this exception might be related to the way I installed towerjs from dev branch https://gist.github.com/3347224  (I do have mongodb running, even there are 5 connections coming on start)

**Comment by edubkendo** [comment] 2012-08-14 07:49
For the record, this log is from the most recent attempt, and while he found a workaround for getting it to run, he was never able to properly create and run an app. My hunch is that the later issues he was having were related to the install issues he had, but it could be two seperate issue. @viatropos please take a look when you can.

```
<DrGigabit> btw, regarding dev branch, if I build it and install using make install; then I try smth. like tower console; I get module.js:340
<DrGigabit>     throw err;
<DrGigabit>           ^
<DrGigabit> Error: Cannot find module '../lib/tower'
<DrGigabit> obviously I don't have tower forked in /usr/local/lib
<e_dub> also, check out  the "Contributor Note" here : https://github.com/viatropos/tower/tree/development   and the roadmap here: https://github.com/viatropos/tower/wiki  ... cuz i think what your talking about is mentioned in one of those... just when you get a chance
<e_dub> ah yeah, you gotta use cake ... hold on, I'll dig up the log where viatropos walked me through install
<DrGigabit> tower@0.4.1 installed into /usr/local/lib/node_modules/tower; but seems it expects the tower folder to be in the /usr/local/lib
<e_dub> ok this is kind of a mess, but: https://gist.github.com/3346889
<e_dub> this may be easier to read: https://dl.dropbox.com/u/24245334/towerjslog.txt
<e_dub> this also: https://dl.dropbox.com/u/24245334/towerlog2.txt DrGigabit 
<e_dub> also made it a gist: https://gist.github.com/3346943
<DrGigabit> the discussion you posted seems to be around desing-io issues; in fact for me everything compiles
<e_dub> so you have everything working fine now?
<e_dub> you can get node to see tower wherever you have it installed by going into that directory and just using "npm link"
<DrGigabit> nope, I can build/install, but cannot run tower console inside the app folder
<DrGigabit> Error: Cannot find module '../lib/tower'
<e_dub> then in projects you make with it, just go into the project and before you run "npm install" , just do, "npm link tower"
<DrGigabit> let me see
<e_dub> and it will link back through the earlier link to where you have tower cloned
<DrGigabit> yes, it did
<DrGigabit> but
<DrGigabit> Error: Cannot find module '../lib/tower'
<DrGigabit> shouldn't it be ../lib/node_modules/tower?
<e_dub> hmm that is odd, yeah
<e_dub> most of my node globals are in usr/local/lib/node_modules and my npm link is linked from there
<e_dub> but it seems like you followed a very different install path from the one i used
<DrGigabit> I just did make build; make install :-)
<e_dub> I forked tower, cloned into a folder in $HOME/git/community, ran npm install, then ran design.io to compile the source to javascript, then did "npm link" as this is what viatropos told me to do
<e_dub> something like that
<e_dub> I thought there was a cake step in there also, but looking back, that was for compiling the client side tower.js file
<DrGigabit> let me try npm install
<e_dub> oh and before i ran design.io to do the compile, I also did, "npm install design.io" and "npm install design.io-javascripts" because those are left out of the package.json file because of heroku or something
<DrGigabit> yes, I also did this step
<e_dub> hmm very weird
<e_dub> can u run any of the tower binary commands?
<DrGigabit> module.js:340
<DrGigabit>     throw err;
<DrGigabit>           ^
<DrGigabit> Error: Cannot find module '../lib/tower'
<DrGigabit>     at Function.Module._resolveFilename (module.js:338:15)
<DrGigabit>     at Function.Module._load (module.js:280:25)
<DrGigabit>     at Module.require (module.js:362:17)
<DrGigabit>     at require (module.js:378:17)
<DrGigabit>     at Object.<anonymous> (/usr/local/lib/node_modules/tower/bin/tower:3:1)
<DrGigabit> obviously this is a path issue
<e_dub> yeah
<DrGigabit> perhaps I should symlink the lib folder
<e_dub> that might work
<DrGigabit> so, here is a workaround: in the /usr/local/lib/node_modules/tower
<DrGigabit> I created lib -> /usr/local/lib/node_modules
<DrGigabit> lib -> /usr/local/lib/node_modules
<DrGigabit> lib pointing to /usr/local/lib/node_modules
<e_dub> that's really weird you had that issue, but definitely good to know about for future
<DrGigabit> seems that generator is not yet stable; /usr/local/lib/node_modules/tower/packages/tower-generator/server/generator.coffee:36
<DrGigabit>       return new klass(options);
<DrGigabit>              ^
<DrGigabit> TypeError: undefined is not a function
<DrGigabit> when I tried tower generate foo with a new towerjs
* Maedi (~maedi@mail.digitalink.com.au) has joined #towerjs
<e_dub> hmm if you read those logs, i got that same error until he pushed a tweak to the generator file
<e_dub> wondering why you are getting it though
<e_dub> I'm gonna make these logs a gist and point viatropos to it so he can take a look at the issues your running into
<e_dub> unless you feel like creating issues
<e_dub> what was the exact "tower generate" command you ran DrGigabit ? I want to try it and see if I get issues
<DrGigabit> tower generate foo
<e_dub> k
<e_dub> ah i get same error, but I'm thinking that's because "foo" is not proper syntax for the generator
<e_dub> try "tower generate scaffold foo"
<DrGigabit> Did you actually try to run any apps generated with the new towerjs? I am trying to "node server" for my existing app, and I get an expection
<DrGigabit>         throw err;
<DrGigabit>               ^
<DrGigabit> TypeError: Cannot read property 'handle' of undefined
<DrGigabit>     at HTTPServer.app.use (/usr/local/lib/node_modules/tower/node_modules/express/lib/http.js:216:17)
<DrGigabit>     at Tower.Application._this [as use] (/usr/local/lib/node_modules/tower/packages/tower-application/server/application.coffee:203:41)
<DrGigabit>     at null.<anonymous> (/Users/avaranovich/projects/SeeUMe/source/seeume/config/bootstrap.coffee:39:10)
<DrGigabit>     at Tower.Application._ref [as stack] (/usr/local/lib/node_modules/tower/packages/tower-application/server/application.coffee:247:16)
<DrGigabit>     at Tower.Application.initializer (/usr/local/lib/node_modules/tower/packages/tower-application/server/application.coffee:168:17)
<DrGigabit>     at Tower.Application._i (/usr/local/lib/node_modules/tower/packages/tower-application/server/application.coffee:237:27)
<DrGigabit>     at _.extend.parallel (/usr/local/lib/node_modules/tower/packages/tower-support/shared/shared.coffee:331:22)
<DrGigabit>     at Tower.StoreMongodbDatabase.ClassMethods.initialize (/usr/local/lib/node_modules/tower/packages/tower-store/server/mongodb/database.coffee:50:26)
<DrGigabit>     at Tower.StoreMongodbDatabase.ClassMethods.initialize.applyIndexes (/usr/local/lib/node_modules/tower/packages/tower-store/server/mongodb/database.coffee:24:22)
<DrGigabit>     at Tower.StoreMongodbDatabase.ClassMethods.initialize (/usr/local/lib/node_modules/tower/packages/tower-store/server/mongodb/database.coffee:48:22)
<DrGigabit> On line 39 I have the following     @use Tower.Middleware.Agent
<e_dub> yeah use either "node server.js" or "tower server -e development"
<DrGigabit> getting the same  /usr/local/lib/node_modules/mongodb/lib/mongodb/connection/server.js:423
<DrGigabit>         throw err;
<DrGigabit>               ^
<DrGigabit> TypeError: Cannot read property 'handle' of undefined
* Maedi_ (~maedi@1.157.31.62) has joined #towerjs
* Maedi has quit (Ping timeout: 272 seconds)
* Maedi_ is now known as Maedi
<DrGigabit> here is an exemption I get https://gist.github.com/3347224
<DrGigabit> the only line related to the app is     at null.<anonymous> (/Users/avaranovich/projects/App/config/bootstrap.coffee:39:10)
<e_dub> do you have an instance of mongodb running on your machine?
<DrGigabit> the trouble is that I have only 28 lines in that file; yes - mongodb is runnig
<e_dub> I just fetched the most recent version of tower --development branch, created a new app, ran npm link tower, npm install, and then ran it with "node server.js"
<e_dub> runs fine
<DrGigabit> did you compile it?
<e_dub> i need to copy a fresh copy of towerjs into my app's vendor folder to get it running in the browser, but the server side stuff is running
<e_dub> did i compile what?
<e_dub> oh what I fetched
<e_dub> no
<e_dub> good point
<DrGigabit> Actually the generator seems does not generate bootstrap.cofee file, so you would not run your app by default anyhow
<DrGigabit> but it now requires bootstrap.coffee by default
<e_dub> ok, things are working here with latest
<DrGigabit> hm
<e_dub> and if i copy this file: https://dl.dropbox.com/u/24245334/tower.js  into /vendor/javascripts in my app, replacing the one thats there, it works in the browser too
<e_dub> make an issue, and copy this irc log into it, so viatropos can see before he merges... some weird stuff going on with your install.  my guess is that its something to do with how you installed, but not sure what at all. 
* Maedi has quit (Quit: Colloquy for iPhone - http://colloquy.mobi)
<DrGigabit> Perhaps we just leave the issue you created
<e_dub> ok, I can add this log as a comment to it, so he can see some of the issues you were running into
<DrGigabit> let me link this expection https://gist.github.com/3347224
<e_dub> ok, hopefully we'll get this all sorted out and make it easier for folks to contribute at the same time
```

**Comment by lancejpollard** [comment] 2012-08-14 15:24
After dev is merged into master, the master branch is going to be what dev is now. At first I thought master should be the same as what's installed with NPM, but the community doesn't seem to do it this way. Instead we'll have version branches like Rails does, and master will be edge.

**Comment by avaranovich** [comment] 2012-08-17 09:23
The issue is more about how to start working with the source code; we where facing multiple issues while trying to build/install tower from sources (in the dev branch).

**Comment by lancejpollard** [comment] 2012-08-21 07:44
@avaranovich Good to know. There's a lot of room for improvement in getting started working with the source code. Will focus on this in the upcoming weeks.

**Comment by lancejpollard** [comment] 2012-09-18 22:04
This should be much easier now and is outlined in the readme: https://github.com/viatropos/tower#contributing-to-tower

**Closed as completed by lancejpollard** 2012-09-18 22:04 UTC
Labels: improvement, needs work
