### ISSUE TITLE
grunt.coffee references lib/tower-tasks/tasks

### ISSUE THREAD

**Issue by neverfox** [tower-archive/tower#381] opened 2013-02-08 08:42 UTC
After creating a new app, `cake watch` was failing to run correctly (though it wasn't giving errors). When I ran grunt directly, I could finally see the error, and it referred to not being able to find `lib/tower-tasks/tasks`. This comes from line 13 of grunt.coffee in the root of my new tower app:

```
require(require('path').join(Tower.srcRoot, 'lib/tower-tasks/tasks'))(grunt)
```

It seems this should instead be `packages/tower-tasks/tasks` and, indeed, cake watch ran fine after making that change. Was that the correct fix?

Now, given that running grunt.coffee (via `cake watch` or otherwise) is a standard step in firing up a new tower app, I'm surprised that this bug, if it is one, seems to have gone unnoticed. That makes me wonder if I'm doing something wrong, following an outdated procedure (because of outdated documentation) or somehow not getting the most up-to-date tower implementation despite installing it today (both globally and locally) directly from the git repository. Any help would be appreciated.

For reference, my procedure for testing was:
1. `tower new myapp`
2. `cd myapp`
3. modify package.json to `"tower": "git://github.com/viatropos/tower.git"`, to incorporate some necessary fixes for Windows
4. `npm install`
5. `cake watch`, from one window
6. `tower server -e development`, from another window

**Comment by thehydroimpulse** [comment] 2013-02-08 20:46
This is most likely related to downloading through github instead of using the npm version. When you install through npm, it'll run some installation scripts. The packages folder is for the source code, and the actually runned files are compiled within the lib folder. I'm assuming the compilation of the coffeescript didn't complete or failed.

Try cd-ing into the tower folder inside node_modules and run `make watch and it'll compile the files.

**Comment by neverfox** [comment] 2013-02-08 21:06
Just to be clear, when I say that I used the github version, I mean as an argument to `npm install`. In other words, I first ran `npm install -g tower`, which gave me the problem I described. Only then did I try `npm install -g git://github.com/viatropos/tower.git`, on a whim. Neither approach gave me a version where `cake watch` worked. Also, coffee-script and grunt are also installed globally in npm.

I'll try your suggestion. Do you mean failing during the npm installation of tower? Any idea as to why this might be happening? If it relies on `make` being available, that could definitely be the issue, given that this is a Windows machine and `make` needs to be explicitly installed.

**Comment by thehydroimpulse** [comment] 2013-02-08 21:49
Ahh, I see.

We had worked on some windows platform fixes a few months ago, but sorta
took them out because of the increasing complexity. Because of that I'm
working on 0.5.0 to work on windows really well, currently using Jake
instead of make (not sure if that'll last - well see).

To work with the towers source code ATM (not includimg 0.5.0) you'll need
make.

Not sure why you're getting that error, never seen that before. Try looking
in your global tower folder for a lib folder. Also check to see if you
haven't installed a local version of tower through npm's repo.

**Comment by neverfox** [comment] 2013-02-08 22:11
I do have the lib folder in my global tower folder. I don't, however, have one in the local version of the new tower app after running `npm install` from the app's folder, which seems to be the cause of the problem. I'm going to try starting from scratch with my node packages after reading about some quirks with node and Windows. In the meantime, would you recommend using your fork of tower at all or is it too unstable?

**Comment by thehydroimpulse** [comment] 2013-02-08 22:21
Once I get home I'll see what the issue is. You should be able to run `npm install` within your app to get started. Do you get any specific errors other than the task one?

The main issues with Tower (prior to 0.5.0) are:
- It uses Make
- Uses unix commands for tests, etc...
- Has some hard coded path separator (/ instead if \ on windows)
- Requires at least two tabs open, which is a problem with windows (unless you're using console2 or something) which has shitty command line system.

I think that's it. Most of the path separators or platform specific things seemed to be fixed for the most part. 

Unfortunately my branch is completely unstable since it has many of the 0.5.0 stuff.

**Comment by neverfox** [comment] 2013-02-08 23:36
Thank you. If you think there is a reasonable set of hacks I could make to 0.4 to patch it for now, I'd be willing to try to make them. Otherwise, it might just be that I have to resign myself to waiting for 0.5.0 before attempting a Tower project. I have a demo app for my job to finish by the beginning of March and I was very much hoping it would be a tower app. Windows isn't optional so, instead, I may have to jump into straight Ember (maybe with Brunch), Knockback or the like. But what drew me to Tower is that I really want something that is full-stack out-of-the-box (node/express/mongodb backend ideally) so that I can concentrate on the app logic and templates rather than hooking up plumbing. Tower seems to be moving in the right direction even if it's not ready for Windows, and the only really similar product of any maturity seems to be CompoundJS.

**Comment by thehydroimpulse** [comment] 2013-02-09 00:12
I do my work on a Windows machine and everything works fine, so it must be an issue with one of the latest patches or changes to the code base. I would suggest to wait for 0.5.0. I consider 0.4.3 to be unstable - both in performance/stability and in efficient environment (make, grunt, impossible client-side development (Tower source)). 

That's the only problem with Ember, it's not a full-stack client/server framework. So you're required to have another server-side mashup which isn't ideal. Lot's of time spent on boilerplate code and not your app. 0.5.0 is going to be much much better. Were leaving the "rails clone" tagline and embarrassing our own unique style. Router, Resources, controllers, models, packages, IoC, events are all new. 

We should have some pretty cool stuff going on in the next few weeks.

**Comment by neverfox** [comment] 2013-02-10 02:20
Running `grunt start --config ./grunt.coffee` from the app's node_modules\tower folder finally built the lib folder, along with other things, and now stuff works. I had also installed make so not sure if that helped. I still don't know why it doesn't run correctly during the original `npm install`; probably something with Unix paths.

**Comment by lancejpollard** [comment] 2013-02-13 08:09
This should be fixed now.

**Closed as completed by lancejpollard** 2013-02-13 08:09 UTC
